# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Lit_UIOPCLdJ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 680)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(900, 680))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_3 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Seach_name = QLabel(self.centralwidget)
        self.Seach_name.setObjectName(u"Seach_name")
        font = QFont()
        font.setFamily(u"\ub098\ub214\uace0\ub515")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Seach_name.setFont(font)

        self.horizontalLayout.addWidget(self.Seach_name)

        self.Seach_input = QLineEdit(self.centralwidget)
        self.Seach_input.setObjectName(u"Seach_input")
        self.Seach_input.setMinimumSize(QSize(0, 30))
        font1 = QFont()
        font1.setFamily(u"\ub098\ub214\uace0\ub515")
        font1.setPointSize(10)
        self.Seach_input.setFont(font1)

        self.horizontalLayout.addWidget(self.Seach_input)


        self.verticalLayout_6.addLayout(self.horizontalLayout)

        self.Shotlayout = QVBoxLayout()
        self.Shotlayout.setObjectName(u"Shotlayout")
        self.Shotlist = QListView(self.centralwidget)
        self.Shotlist.setObjectName(u"Shotlist")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Shotlist.sizePolicy().hasHeightForWidth())
        self.Shotlist.setSizePolicy(sizePolicy1)
        self.Shotlist.setFont(font1)

        self.Shotlayout.addWidget(self.Shotlist)


        self.verticalLayout_6.addLayout(self.Shotlayout)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.Refresh_btn = QPushButton(self.centralwidget)
        self.Refresh_btn.setObjectName(u"Refresh_btn")
        self.Refresh_btn.setMinimumSize(QSize(0, 30))
        self.Refresh_btn.setFont(font1)

        self.verticalLayout_3.addWidget(self.Refresh_btn)


        self.verticalLayout_6.addLayout(self.verticalLayout_3)

        self.datalayout = QVBoxLayout()
        self.datalayout.setObjectName(u"datalayout")
        self.datalist = QTableView(self.centralwidget)
        self.datalist.setObjectName(u"datalist")
        self.datalist.setFont(font1)

        self.datalayout.addWidget(self.datalist)


        self.verticalLayout_6.addLayout(self.datalayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.export_All = QPushButton(self.centralwidget)
        self.export_All.setObjectName(u"export_All")
        self.export_All.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.export_All.sizePolicy().hasHeightForWidth())
        self.export_All.setSizePolicy(sizePolicy2)
        self.export_All.setMinimumSize(QSize(0, 60))
        self.export_All.setFont(font1)

        self.verticalLayout.addWidget(self.export_All)


        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.import_All = QPushButton(self.centralwidget)
        self.import_All.setObjectName(u"import_All")
        self.import_All.setMinimumSize(QSize(0, 60))
        self.import_All.setFont(font1)

        self.verticalLayout_2.addWidget(self.import_All)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)


        self.verticalLayout_6.addLayout(self.horizontalLayout_2)


        self.horizontalLayout_3.addLayout(self.verticalLayout_6)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout_3.addWidget(self.line)

        self.Tool_Tab = QTabWidget(self.centralwidget)
        self.Tool_Tab.setObjectName(u"Tool_Tab")
        sizePolicy.setHeightForWidth(self.Tool_Tab.sizePolicy().hasHeightForWidth())
        self.Tool_Tab.setSizePolicy(sizePolicy)
        self.Tool_Tab.setMinimumSize(QSize(500, 620))
        font2 = QFont()
        font2.setFamily(u"\ub098\ub214\uace0\ub515")
        self.Tool_Tab.setFont(font2)
        self.Render = QWidget()
        self.Render.setObjectName(u"Render")
        self.render_set_JH = QPushButton(self.Render)
        self.render_set_JH.setObjectName(u"render_set_JH")
        self.render_set_JH.setGeometry(QRect(10, 60, 91, 41))
        self.render_set_SA = QPushButton(self.Render)
        self.render_set_SA.setObjectName(u"render_set_SA")
        self.render_set_SA.setGeometry(QRect(110, 60, 91, 41))
        self.Render_set = QLabel(self.Render)
        self.Render_set.setObjectName(u"Render_set")
        self.Render_set.setGeometry(QRect(10, 30, 111, 21))
        font3 = QFont()
        font3.setFamily(u"\ub098\ub214\uace0\ub515")
        font3.setBold(True)
        font3.setWeight(75)
        self.Render_set.setFont(font3)
        self.sampling_Mid = QPushButton(self.Render)
        self.sampling_Mid.setObjectName(u"sampling_Mid")
        self.sampling_Mid.setGeometry(QRect(110, 220, 91, 41))
        self.sampling_low = QPushButton(self.Render)
        self.sampling_low.setObjectName(u"sampling_low")
        self.sampling_low.setGeometry(QRect(10, 220, 91, 41))
        self.sampling_low.setMouseTracking(False)
        self.Sampling = QLabel(self.Render)
        self.Sampling.setObjectName(u"Sampling")
        self.Sampling.setGeometry(QRect(10, 190, 111, 21))
        self.Sampling.setFont(font3)
        self.sampling_High = QPushButton(self.Render)
        self.sampling_High.setObjectName(u"sampling_High")
        self.sampling_High.setGeometry(QRect(210, 220, 91, 41))
        self.sampling_Vol = QPushButton(self.Render)
        self.sampling_Vol.setObjectName(u"sampling_Vol")
        self.sampling_Vol.setGeometry(QRect(10, 270, 91, 41))
        self.sampling_Fil = QPushButton(self.Render)
        self.sampling_Fil.setObjectName(u"sampling_Fil")
        self.sampling_Fil.setGeometry(QRect(110, 270, 91, 41))
        self.render_set_Deep = QPushButton(self.Render)
        self.render_set_Deep.setObjectName(u"render_set_Deep")
        self.render_set_Deep.setGeometry(QRect(210, 60, 91, 41))
        self.render_set_W = QPushButton(self.Render)
        self.render_set_W.setObjectName(u"render_set_W")
        self.render_set_W.setGeometry(QRect(10, 110, 91, 41))
        self.Tool_Tab.addTab(self.Render, "")
        self.render_set_JH.raise_()
        self.render_set_SA.raise_()
        self.Render_set.raise_()
        self.sampling_Mid.raise_()
        self.Sampling.raise_()
        self.sampling_High.raise_()
        self.sampling_Vol.raise_()
        self.sampling_Fil.raise_()
        self.render_set_Deep.raise_()
        self.render_set_W.raise_()
        self.sampling_low.raise_()
        self.Light = QWidget()
        self.Light.setObjectName(u"Light")
        self.Lit_btn = QPushButton(self.Light)
        self.Lit_btn.setObjectName(u"Lit_btn")
        self.Lit_btn.setGeometry(QRect(270, 120, 81, 31))
        self.Normal_txt = QLabel(self.Light)
        self.Normal_txt.setObjectName(u"Normal_txt")
        self.Normal_txt.setGeometry(QRect(10, 240, 111, 31))
        self.Normal_OFF = QRadioButton(self.Light)
        self.Normal_OFF.setObjectName(u"Normal_OFF")
        self.Normal_OFF.setGeometry(QRect(210, 240, 51, 31))
        self.Rivet = QPushButton(self.Light)
        self.Rivet.setObjectName(u"Rivet")
        self.Rivet.setGeometry(QRect(210, 60, 91, 41))
        self.LG_btn = QPushButton(self.Light)
        self.LG_btn.setObjectName(u"LG_btn")
        self.LG_btn.setGeometry(QRect(270, 320, 81, 31))
        self.LG_type = QComboBox(self.Light)
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.addItem("")
        self.LG_type.setObjectName(u"LG_type")
        self.LG_type.setGeometry(QRect(130, 320, 131, 31))
        font4 = QFont()
        font4.setFamily(u"\uad74\ub9bc")
        font4.setPointSize(10)
        self.LG_type.setFont(font4)
        self.LG_type.setEditable(True)
        self.Lit_type = QComboBox(self.Light)
        self.Lit_type.addItem("")
        self.Lit_type.addItem("")
        self.Lit_type.addItem("")
        self.Lit_type.addItem("")
        self.Lit_type.addItem("")
        self.Lit_type.setObjectName(u"Lit_type")
        self.Lit_type.setGeometry(QRect(10, 120, 91, 31))
        self.Lit_type.setFont(font4)
        self.Lit_type.setEditable(True)
        self.LG_txt = QLabel(self.Light)
        self.LG_txt.setObjectName(u"LG_txt")
        self.LG_txt.setGeometry(QRect(10, 320, 111, 31))
        self.LG_txt.setFont(font4)
        self.Lit_name = QLineEdit(self.Light)
        self.Lit_name.setObjectName(u"Lit_name")
        self.Lit_name.setGeometry(QRect(110, 120, 151, 31))
        self.Lit_name.setFont(font4)
        self.CH_lit = QPushButton(self.Light)
        self.CH_lit.setObjectName(u"CH_lit")
        self.CH_lit.setGeometry(QRect(110, 60, 91, 41))
        self.Basic_lit = QPushButton(self.Light)
        self.Basic_lit.setObjectName(u"Basic_lit")
        self.Basic_lit.setGeometry(QRect(10, 60, 91, 41))
        self.Normal_ON = QRadioButton(self.Light)
        self.Normal_ON.setObjectName(u"Normal_ON")
        self.Normal_ON.setGeometry(QRect(140, 240, 51, 31))
        self.LIGHT_setting = QLabel(self.Light)
        self.LIGHT_setting.setObjectName(u"LIGHT_setting")
        self.LIGHT_setting.setGeometry(QRect(10, 30, 271, 21))
        self.LIGHT_setting.setFont(font3)
        self.Normal_btn = QPushButton(self.Light)
        self.Normal_btn.setObjectName(u"Normal_btn")
        self.Normal_btn.setGeometry(QRect(270, 240, 81, 31))
        self.LIGHT_Attribute = QLabel(self.Light)
        self.LIGHT_Attribute.setObjectName(u"LIGHT_Attribute")
        self.LIGHT_Attribute.setGeometry(QRect(10, 210, 251, 21))
        self.LIGHT_Attribute.setFont(font3)
        self.Lit_AT_value = QLineEdit(self.Light)
        self.Lit_AT_value.setObjectName(u"Lit_AT_value")
        self.Lit_AT_value.setGeometry(QRect(130, 280, 131, 31))
        self.Lit_AT_value.setFont(font4)
        self.Lit_AT_btn = QPushButton(self.Light)
        self.Lit_AT_btn.setObjectName(u"Lit_AT_btn")
        self.Lit_AT_btn.setGeometry(QRect(270, 280, 81, 31))
        self.Lit_AT_type = QComboBox(self.Light)
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.addItem("")
        self.Lit_AT_type.setObjectName(u"Lit_AT_type")
        self.Lit_AT_type.setGeometry(QRect(10, 280, 111, 31))
        self.Lit_AT_type.setFont(font4)
        self.Lit_AT_type.setEditable(True)
        self.Tool_Tab.addTab(self.Light, "")
        self.Layer = QWidget()
        self.Layer.setObjectName(u"Layer")
        self.Set_setting = QLabel(self.Layer)
        self.Set_setting.setObjectName(u"Set_setting")
        self.Set_setting.setGeometry(QRect(10, 30, 111, 21))
        self.Set_setting.setFont(font3)
        self.Basic_set = QPushButton(self.Layer)
        self.Basic_set.setObjectName(u"Basic_set")
        self.Basic_set.setGeometry(QRect(10, 60, 91, 41))
        self.Layer_setting = QLabel(self.Layer)
        self.Layer_setting.setObjectName(u"Layer_setting")
        self.Layer_setting.setGeometry(QRect(10, 130, 111, 21))
        self.Layer_setting.setFont(font3)
        self.Basic_layer = QPushButton(self.Layer)
        self.Basic_layer.setObjectName(u"Basic_layer")
        self.Basic_layer.setGeometry(QRect(10, 160, 91, 41))
        self.Utill_layer = QPushButton(self.Layer)
        self.Utill_layer.setObjectName(u"Utill_layer")
        self.Utill_layer.setGeometry(QRect(110, 160, 91, 41))
        self.CH_layer = QPushButton(self.Layer)
        self.CH_layer.setObjectName(u"CH_layer")
        self.CH_layer.setGeometry(QRect(10, 210, 91, 41))
        self.BG_layer = QPushButton(self.Layer)
        self.BG_layer.setObjectName(u"BG_layer")
        self.BG_layer.setGeometry(QRect(110, 210, 91, 41))
        self.SH_layer = QPushButton(self.Layer)
        self.SH_layer.setObjectName(u"SH_layer")
        self.SH_layer.setGeometry(QRect(210, 210, 91, 41))
        self.Tool_Tab.addTab(self.Layer, "")
        self.AOV = QWidget()
        self.AOV.setObjectName(u"AOV")
        self.ToonUtill = QPushButton(self.AOV)
        self.ToonUtill.setObjectName(u"ToonUtill")
        self.ToonUtill.setGeometry(QRect(110, 310, 91, 41))
        self.SamplerInfo = QPushButton(self.AOV)
        self.SamplerInfo.setObjectName(u"SamplerInfo")
        self.SamplerInfo.setGeometry(QRect(10, 310, 91, 41))
        self.Basic_aov = QPushButton(self.AOV)
        self.Basic_aov.setObjectName(u"Basic_aov")
        self.Basic_aov.setGeometry(QRect(10, 220, 91, 41))
        self.Toon_aov = QPushButton(self.AOV)
        self.Toon_aov.setObjectName(u"Toon_aov")
        self.Toon_aov.setGeometry(QRect(210, 310, 91, 41))
        self.Toon_make = QLabel(self.AOV)
        self.Toon_make.setObjectName(u"Toon_make")
        self.Toon_make.setGeometry(QRect(10, 280, 111, 21))
        self.Toon_make.setFont(font3)
        self.AOV_make = QLabel(self.AOV)
        self.AOV_make.setObjectName(u"AOV_make")
        self.AOV_make.setGeometry(QRect(10, 190, 111, 21))
        self.AOV_make.setFont(font3)
        self.occ_aov = QPushButton(self.AOV)
        self.occ_aov.setObjectName(u"occ_aov")
        self.occ_aov.setGeometry(QRect(110, 220, 91, 41))
        self.crypto_aov = QPushButton(self.AOV)
        self.crypto_aov.setObjectName(u"crypto_aov")
        self.crypto_aov.setGeometry(QRect(210, 220, 91, 41))
        self.lit_aov = QPushButton(self.AOV)
        self.lit_aov.setObjectName(u"lit_aov")
        self.lit_aov.setGeometry(QRect(310, 220, 91, 41))
        self.AOV_btn = QPushButton(self.AOV)
        self.AOV_btn.setObjectName(u"AOV_btn")
        self.AOV_btn.setGeometry(QRect(270, 130, 81, 31))
        self.AOV_enable = QLabel(self.AOV)
        self.AOV_enable.setObjectName(u"AOV_enable")
        self.AOV_enable.setGeometry(QRect(10, 130, 71, 31))
        self.AOV_OFF = QRadioButton(self.AOV)
        self.AOV_OFF.setObjectName(u"AOV_OFF")
        self.AOV_OFF.setGeometry(QRect(180, 130, 90, 31))
        self.AOV_ONOFF = QLabel(self.AOV)
        self.AOV_ONOFF.setObjectName(u"AOV_ONOFF")
        self.AOV_ONOFF.setGeometry(QRect(10, 100, 111, 21))
        self.AOV_ONOFF.setFont(font3)
        self.AOV_ON = QRadioButton(self.AOV)
        self.AOV_ON.setObjectName(u"AOV_ON")
        self.AOV_ON.setGeometry(QRect(90, 130, 90, 31))
        self.OFF_Aovset = QPushButton(self.AOV)
        self.OFF_Aovset.setObjectName(u"OFF_Aovset")
        self.OFF_Aovset.setGeometry(QRect(10, 30, 161, 41))
        self.Tool_Tab.addTab(self.AOV, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.Project_aov_set = QLabel(self.tab)
        self.Project_aov_set.setObjectName(u"Project_aov_set")
        self.Project_aov_set.setGeometry(QRect(10, 30, 111, 21))
        self.Project_aov_set.setFont(font3)
        self.FX_lit = QPushButton(self.tab)
        self.FX_lit.setObjectName(u"FX_lit")
        self.FX_lit.setGeometry(QRect(10, 300, 91, 41))
        self.FX_set = QPushButton(self.tab)
        self.FX_set.setObjectName(u"FX_set")
        self.FX_set.setGeometry(QRect(110, 300, 91, 41))
        self.FX_layer = QPushButton(self.tab)
        self.FX_layer.setObjectName(u"FX_layer")
        self.FX_layer.setGeometry(QRect(210, 300, 91, 41))
        self.verticalLayoutWidget_6 = QWidget(self.tab)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(10, 60, 401, 131))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.Project_list = QListView(self.verticalLayoutWidget_6)
        self.Project_list.setObjectName(u"Project_list")
        self.Project_list.setFont(font1)

        self.verticalLayout_4.addWidget(self.Project_list)

        self.Project_input = QLineEdit(self.tab)
        self.Project_input.setObjectName(u"Project_input")
        self.Project_input.setGeometry(QRect(10, 200, 261, 31))
        self.verticalLayoutWidget_7 = QWidget(self.tab)
        self.verticalLayoutWidget_7.setObjectName(u"verticalLayoutWidget_7")
        self.verticalLayoutWidget_7.setGeometry(QRect(280, 200, 131, 32))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.Project_export_btn = QPushButton(self.verticalLayoutWidget_7)
        self.Project_export_btn.setObjectName(u"Project_export_btn")
        self.Project_export_btn.setMinimumSize(QSize(0, 30))

        self.verticalLayout_5.addWidget(self.Project_export_btn)

        self.verticalLayoutWidget_9 = QWidget(self.tab)
        self.verticalLayoutWidget_9.setObjectName(u"verticalLayoutWidget_9")
        self.verticalLayoutWidget_9.setGeometry(QRect(10, 240, 261, 32))
        self.verticalLayout_8 = QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.Project_refresh = QPushButton(self.verticalLayoutWidget_9)
        self.Project_refresh.setObjectName(u"Project_refresh")
        self.Project_refresh.setMinimumSize(QSize(0, 30))

        self.verticalLayout_8.addWidget(self.Project_refresh)

        self.verticalLayoutWidget_8 = QWidget(self.tab)
        self.verticalLayoutWidget_8.setObjectName(u"verticalLayoutWidget_8")
        self.verticalLayoutWidget_8.setGeometry(QRect(280, 240, 131, 32))
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.Project_import_btn = QPushButton(self.verticalLayoutWidget_8)
        self.Project_import_btn.setObjectName(u"Project_import_btn")
        self.Project_import_btn.setMinimumSize(QSize(0, 30))

        self.verticalLayout_7.addWidget(self.Project_import_btn)

        self.beam_set = QPushButton(self.tab)
        self.beam_set.setObjectName(u"beam_set")
        self.beam_set.setGeometry(QRect(10, 360, 91, 41))
        self.beam_lit = QPushButton(self.tab)
        self.beam_lit.setObjectName(u"beam_lit")
        self.beam_lit.setGeometry(QRect(110, 360, 91, 41))
        self.fog_btn = QPushButton(self.tab)
        self.fog_btn.setObjectName(u"fog_btn")
        self.fog_btn.setGeometry(QRect(210, 360, 91, 41))
        self.Tool_Tab.addTab(self.tab, "")

        self.horizontalLayout_3.addWidget(self.Tool_Tab)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.Tool_Tab.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Lit_tool_240131", None))
        self.Seach_name.setText(QCoreApplication.translate("MainWindow", u"seach :", None))
        self.Refresh_btn.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.export_All.setText(QCoreApplication.translate("MainWindow", u"All_Export", None))
        self.import_All.setText(QCoreApplication.translate("MainWindow", u"All_Import", None))
        self.render_set_JH.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.render_set_SA.setText(QCoreApplication.translate("MainWindow", u"Old", None))
        self.Render_set.setText(QCoreApplication.translate("MainWindow", u"Render_set", None))
        self.sampling_Mid.setText(QCoreApplication.translate("MainWindow", u"MIDDLE", None))
        self.sampling_low.setText(QCoreApplication.translate("MainWindow", u"LOW", None))
        self.Sampling.setText(QCoreApplication.translate("MainWindow", u"Sampling", None))
        self.sampling_High.setText(QCoreApplication.translate("MainWindow", u"HIGH", None))
        self.sampling_Vol.setText(QCoreApplication.translate("MainWindow", u"VOLUME", None))
        self.sampling_Fil.setText(QCoreApplication.translate("MainWindow", u"Flickr", None))
        self.render_set_Deep.setText(QCoreApplication.translate("MainWindow", u"Deep", None))
        self.render_set_W.setText(QCoreApplication.translate("MainWindow", u"W_default", None))
        self.Tool_Tab.setTabText(self.Tool_Tab.indexOf(self.Render), QCoreApplication.translate("MainWindow", u"Render", None))
        self.Lit_btn.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.Normal_txt.setText(QCoreApplication.translate("MainWindow", u"NormallIze :", None))
        self.Normal_OFF.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.Rivet.setText(QCoreApplication.translate("MainWindow", u"Rivet", None))
        self.LG_btn.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.LG_type.setItemText(0, "")
        self.LG_type.setItemText(1, QCoreApplication.translate("MainWindow", u"dome", None))
        self.LG_type.setItemText(2, QCoreApplication.translate("MainWindow", u"key", None))
        self.LG_type.setItemText(3, QCoreApplication.translate("MainWindow", u"keyadd", None))
        self.LG_type.setItemText(4, QCoreApplication.translate("MainWindow", u"fill", None))
        self.LG_type.setItemText(5, QCoreApplication.translate("MainWindow", u"back", None))
        self.LG_type.setItemText(6, QCoreApplication.translate("MainWindow", u"rim", None))
        self.LG_type.setItemText(7, QCoreApplication.translate("MainWindow", u"bounce", None))

        self.Lit_type.setItemText(0, QCoreApplication.translate("MainWindow", u"area", None))
        self.Lit_type.setItemText(1, QCoreApplication.translate("MainWindow", u"point", None))
        self.Lit_type.setItemText(2, QCoreApplication.translate("MainWindow", u"spot", None))
        self.Lit_type.setItemText(3, QCoreApplication.translate("MainWindow", u"direftional", None))
        self.Lit_type.setItemText(4, QCoreApplication.translate("MainWindow", u"dome", None))

        self.LG_txt.setText(QCoreApplication.translate("MainWindow", u"Light Group :", None))
        self.CH_lit.setText(QCoreApplication.translate("MainWindow", u"CH_lit", None))
        self.Basic_lit.setText(QCoreApplication.translate("MainWindow", u"Basic_lit", None))
        self.Normal_ON.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.LIGHT_setting.setText(QCoreApplication.translate("MainWindow", u"LIGHT_setting", None))
        self.Normal_btn.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.LIGHT_Attribute.setText(QCoreApplication.translate("MainWindow", u"LIGHT_Attribute", None))
        self.Lit_AT_btn.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.Lit_AT_type.setItemText(0, QCoreApplication.translate("MainWindow", u"intensity", None))
        self.Lit_AT_type.setItemText(1, QCoreApplication.translate("MainWindow", u"exposure", None))
        self.Lit_AT_type.setItemText(2, QCoreApplication.translate("MainWindow", u"aiSpread", None))
        self.Lit_AT_type.setItemText(3, QCoreApplication.translate("MainWindow", u"aiCamera", None))
        self.Lit_AT_type.setItemText(4, QCoreApplication.translate("MainWindow", u"aiTransmission", None))
        self.Lit_AT_type.setItemText(5, QCoreApplication.translate("MainWindow", u"aiDiffuse", None))
        self.Lit_AT_type.setItemText(6, QCoreApplication.translate("MainWindow", u"aiSpecular", None))
        self.Lit_AT_type.setItemText(7, QCoreApplication.translate("MainWindow", u"aiSss", None))
        self.Lit_AT_type.setItemText(8, QCoreApplication.translate("MainWindow", u"aiIndirect", None))
        self.Lit_AT_type.setItemText(9, QCoreApplication.translate("MainWindow", u"aiVolume", None))
        self.Lit_AT_type.setItemText(10, QCoreApplication.translate("MainWindow", u"aiSamples", None))

        self.Tool_Tab.setTabText(self.Tool_Tab.indexOf(self.Light), QCoreApplication.translate("MainWindow", u"Light", None))
        self.Set_setting.setText(QCoreApplication.translate("MainWindow", u"SET_setting", None))
        self.Basic_set.setText(QCoreApplication.translate("MainWindow", u"Basic_set", None))
        self.Layer_setting.setText(QCoreApplication.translate("MainWindow", u"LAYER_setting", None))
        self.Basic_layer.setText(QCoreApplication.translate("MainWindow", u"Basic_Layer", None))
        self.Utill_layer.setText(QCoreApplication.translate("MainWindow", u"Utill_Layer", None))
        self.CH_layer.setText(QCoreApplication.translate("MainWindow", u"CH_Layer", None))
        self.BG_layer.setText(QCoreApplication.translate("MainWindow", u"BG_Layer", None))
        self.SH_layer.setText(QCoreApplication.translate("MainWindow", u"SH_Layer", None))
        self.Tool_Tab.setTabText(self.Tool_Tab.indexOf(self.Layer), QCoreApplication.translate("MainWindow", u"Layer", None))
        self.ToonUtill.setText(QCoreApplication.translate("MainWindow", u"ToonUtill", None))
        self.SamplerInfo.setText(QCoreApplication.translate("MainWindow", u"SamplerInfo", None))
        self.Basic_aov.setText(QCoreApplication.translate("MainWindow", u"Basic_aov", None))
        self.Toon_aov.setText(QCoreApplication.translate("MainWindow", u"Toon_aov", None))
        self.Toon_make.setText(QCoreApplication.translate("MainWindow", u"Toon_make", None))
        self.AOV_make.setText(QCoreApplication.translate("MainWindow", u"AOV_make", None))
        self.occ_aov.setText(QCoreApplication.translate("MainWindow", u"occ_aov", None))
        self.crypto_aov.setText(QCoreApplication.translate("MainWindow", u"crypto_aov", None))
        self.lit_aov.setText(QCoreApplication.translate("MainWindow", u"lit_aov", None))
        self.AOV_btn.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.AOV_enable.setText(QCoreApplication.translate("MainWindow", u"AOV Enable:", None))
        self.AOV_OFF.setText(QCoreApplication.translate("MainWindow", u"OFF", None))
        self.AOV_ONOFF.setText(QCoreApplication.translate("MainWindow", u"AOV_ON/OFF", None))
        self.AOV_ON.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.OFF_Aovset.setText(QCoreApplication.translate("MainWindow", u"AllOFF_Aovset", None))
        self.Tool_Tab.setTabText(self.Tool_Tab.indexOf(self.AOV), QCoreApplication.translate("MainWindow", u"AOV", None))
        self.Project_aov_set.setText(QCoreApplication.translate("MainWindow", u"Project_set", None))
        self.FX_lit.setText(QCoreApplication.translate("MainWindow", u"FX_meshlit", None))
        self.FX_set.setText(QCoreApplication.translate("MainWindow", u"FX_set", None))
        self.FX_layer.setText(QCoreApplication.translate("MainWindow", u"FX_Layer", None))
        self.Project_export_btn.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.Project_refresh.setText(QCoreApplication.translate("MainWindow", u"Refesh", None))
        self.Project_import_btn.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.beam_set.setText(QCoreApplication.translate("MainWindow", u"beam_set", None))
        self.beam_lit.setText(QCoreApplication.translate("MainWindow", u"beam_lit", None))
        self.fog_btn.setText(QCoreApplication.translate("MainWindow", u"fog", None))
        self.Tool_Tab.setTabText(self.Tool_Tab.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Project", None))
    # retranslateUi

